#!/bin/zsh

export RESET='\e[0m';

export BG_RESET='\e[49m';
export BG_BLACK='\e[40m';
export BG_RED='\e[41m';
export BG_GREEN='\e[42m';
export BG_YELLOW='\e[43m';
export BG_BLUE='\e[44m';
export BG_MAGENTA='\e[45m';
export BG_CYAN='\e[46m';
export BG_LIGHT_GRAY='\e[47m';
export BG_DARK_GRAY='\e[100';
export BG_LIGHT_RED='\e[101';
export BG_LIGHT_GREEN='\e[102';
export BG_LIGHT_YELLO='\e[103';
export BG_LIGHT_BLUE='\e[104';
export BG_LIGHT_MAGENT='\e[105';
export BG_LIGHT_CYAN='\e[106';
export BG_WHITE='\e[107';

export BLACK='\e[30m';
export RED='\e[31m';
export GREEN='\e[32m';
export YELLOW='\e[33m';
export BLUE='\e[34m';
export MAGENTA='\e[35m';
export CYAN='\e[36m';
export LIGHT_GRAY='\e[37m';
export DARK_GRAY='\e[90m';
export LIGHT_RED='\e[91m';
export LIGHT_GREEN='\e[92m';
export LIGHT_YELLOW='\e[93m';
export LIGHT_BLUE='\e[94m';
export LIGHT_MAGENTA='\e[95m';
export LIGHT_CYAN='\e[96m';
export WHITE='\e[97m';

export BOLD='\e[1m'
export DIM='\e[2m'
export UNDERLINE='\e[4m'
export BLINK='\e[5m'
